# Generated by Django 2.1.7 on 2019-03-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=200)),
                ('feat_artist_name', models.CharField(max_length=200)),
                ('view_count', models.IntegerField(default=0)),
                ('sub_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Graph',
        ),
    ]
