# Generated by Django 2.1.7 on 2019-03-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0004_auto_20190327_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphitem',
            name='genre',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='graphitem',
            name='yt_channel_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='graphitem',
            name='yt_channel_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
