# Generated by Django 2.1.7 on 2019-03-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0005_auto_20190327_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongsItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(default=None, max_length=200)),
                ('feat_artist', models.CharField(default=None, max_length=200)),
                ('song', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='graphitem',
            name='song',
        ),
        migrations.AddField(
            model_name='graphitem',
            name='num_feats',
            field=models.IntegerField(default=0),
        ),
    ]
