# Generated by Django 2.1.7 on 2019-03-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0006_auto_20190328_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphitem',
            name='genre',
            field=models.CharField(default='Other', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='songsitems',
            name='artist',
            field=models.CharField(default='Unknown artist', max_length=200),
        ),
        migrations.AlterField(
            model_name='songsitems',
            name='feat_artist',
            field=models.CharField(default='Unknown artist', max_length=200),
        ),
        migrations.AlterField(
            model_name='songsitems',
            name='song',
            field=models.CharField(default='Unknown song', max_length=200),
        ),
    ]
